# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: env
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-polferov'
    repository: 'polferov/kvg2'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest
- task: AzureCLI@2
  inputs:
    azureSubscription: 'kvg2'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'deploy.sh'
