# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-polferov'
    command: 'login'
- script: |
    # docker run --privileged --rm tonistiigi/binfmt --install arm64
    docker buildx create --use
    docker buildx build \
      --platform linux/amd64,linux/arm64/v8 \
      -t polferov/kvg2:latest \
      -t polferov/kvg2:$(Build.BuildId) \
      --push \
      .