# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-polferov'
    repository: 'polferov/kvg2'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest
- task: AzureCLI@2
  inputs:
    azureSubscription: 'kvg2'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az extension add --upgrade --name containerapp
      export CURRENT=$(az containerapp revision list --name kvg2 --resource-group kvg2 | grep '"name"' | grep '"kvg2--' | tail -n 1 | sed 's/ *"name": *"//g' | sed -r 's/",?$//')
      az containerapp revision copy --resource-group kvg2 --name kvg2 --image "polferov/kvg2:$BUILD_BUILDID" --from-revision "$CURRENT"